/* eslint-disable @typescript-eslint/ban-ts-comment */
// @ts-nocheck - Types are generated by Convex at deploy time
/**
 * Scheduled Jobs for FaxBella
 *
 * - Monthly fax count reset (1st of each month)
 * - Document retention enforcement (daily)
 */

import { cronJobs } from 'convex/server';
import { internal } from './_generated/api';

const crons = cronJobs();

// Reset monthly fax counts on the 1st of each month at midnight UTC
crons.monthly(
    'reset monthly fax counts',
    { day: 1, hourUTC: 0, minuteUTC: 0 },
    internal.customers.resetMonthlyCounts,
);

// Enforce document retention policy daily at 3am UTC
crons.daily(
    'enforce document retention',
    { hourUTC: 3, minuteUTC: 0 },
    internal.documentLibrary.enforceRetentionPolicy,
);

export default crons;
