/* eslint-disable @typescript-eslint/ban-ts-comment */
// @ts-nocheck - Types are generated by Convex at deploy time
/**
 * File Access Layer for FaxBella
 *
 * Public actions for generating presigned download URLs.
 * Internal queries for ownership-verified fax lookups.
 * All access is gated by customer email ownership verification.
 */

import { action, internalQuery } from './_generated/server';
import { internal } from './_generated/api';
import { v } from 'convex/values';

/* ─── Internal Queries (ownership-verified lookups) ─── */

/**
 * Get an inbound fax by ID, only if it belongs to the given customer.
 */
export const getInboundFaxInternal = internalQuery({
    args: {
        faxId: v.id('inboundFaxes'),
        customerId: v.id('customers'),
    },
    handler: async (ctx, args) => {
        const fax = await ctx.db.get(args.faxId);
        if (!fax || fax.customerId !== args.customerId) return null;
        return { r2ObjectKey: fax.r2ObjectKey, fileName: fax.fileName };
    },
});

/**
 * Get an outbound fax by ID, only if it belongs to the given customer.
 */
export const getOutboundFaxInternal = internalQuery({
    args: {
        faxId: v.id('outboundFaxes'),
        customerId: v.id('customers'),
    },
    handler: async (ctx, args) => {
        const fax = await ctx.db.get(args.faxId);
        if (!fax || fax.customerId !== args.customerId) return null;
        return { r2ObjectKey: fax.r2ObjectKey, fileName: fax.fileName };
    },
});

/* ─── Public Actions ──────────────────────────────────── */

/**
 * Get a presigned download URL for a fax document.
 * Verifies customer ownership before generating the URL.
 */
export const getDownloadUrl = action({
    args: {
        email: v.string(),
        faxId: v.string(),
        direction: v.union(v.literal('inbound'), v.literal('outbound')),
    },
    handler: async (ctx, args) => {
        // Look up the customer
        const customer = await ctx.runQuery(internal.customers.getCustomerByEmail, {
            email: args.email,
        });
        if (!customer) {
            throw new Error('Customer not found');
        }

        // Validate faxId format before passing to typed internal queries
        if (!args.faxId || typeof args.faxId !== 'string') {
            throw new Error('Invalid fax ID');
        }

        // Look up the fax record and verify ownership
        let r2ObjectKey: string | undefined;

        if (args.direction === 'inbound') {
            const fax = await ctx.runQuery(internal.fileAccess.getInboundFaxInternal, {
                faxId: args.faxId as any,
                customerId: customer._id,
            });
            if (!fax) {
                throw new Error('Fax not found or access denied');
            }
            r2ObjectKey = fax.r2ObjectKey;
        } else {
            const fax = await ctx.runQuery(internal.fileAccess.getOutboundFaxInternal, {
                faxId: args.faxId as any,
                customerId: customer._id,
            });
            if (!fax) {
                throw new Error('Fax not found or access denied');
            }
            r2ObjectKey = fax.r2ObjectKey;
        }

        if (!r2ObjectKey) {
            throw new Error('No file associated with this fax');
        }

        // Generate presigned download URL via R2 internal action
        const result = await ctx.runAction(internal.r2.getPresignedDownloadUrlInternal, {
            objectKey: r2ObjectKey,
        });

        return { downloadUrl: result.downloadUrl };
    },
});
