/* eslint-disable @typescript-eslint/ban-ts-comment */
// @ts-nocheck - Types are generated by Convex at deploy time
/**
 * Email Notification Module for FaxBella
 *
 * Centralized email notifications sent via EmailIt (api.emailit.com).
 * All functions are internalActions -- server-side only, never exposed to clients.
 * Email failure never blocks fax processing; errors are logged and swallowed.
 */

import { internalAction } from './_generated/server';
import { v } from 'convex/values';

// ---------------------------------------------------------------------------
// Design tokens (mirrored from globals.css / brand guide)
// ---------------------------------------------------------------------------

const BRAND_ACCENT = '#e8553d';
const COLOR_DARK = '#1e293b';
const COLOR_LIGHT_BG = '#f5f5f5';
const COLOR_WHITE = '#ffffff';
const COLOR_TEXT_PRIMARY = '#1a1a1a';
const COLOR_TEXT_SECONDARY = '#64748b';
const COLOR_TEXT_TERTIARY = '#94a3b8';
const FONT_STACK =
    "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif";

const BASE_URL = 'https://faxbella.com';
const FROM_ADDRESS = 'FaxBella <notifications@faxbella.com>';
const EMAILIT_ENDPOINT = 'https://api.emailit.com/v1/emails';

// ---------------------------------------------------------------------------
// Shared email template builder
// ---------------------------------------------------------------------------

interface EmailTemplateOptions {
    headerGradient: string;
    headerIcon: string;
    headerTitle: string;
    bodyHtml: string;
    ctaText: string;
    ctaUrl: string;
}

function buildEmailHtml(options: EmailTemplateOptions): string {
    const { headerGradient, headerIcon, headerTitle, bodyHtml, ctaText, ctaUrl } =
        options;

    return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>${headerTitle}</title>
<!--[if mso]>
<noscript>
<xml>
<o:OfficeDocumentSettings>
<o:PixelsPerInch>96</o:PixelsPerInch>
</o:OfficeDocumentSettings>
</xml>
</noscript>
<![endif]-->
</head>
<body style="margin:0;padding:0;background-color:${COLOR_LIGHT_BG};font-family:${FONT_STACK};-webkit-font-smoothing:antialiased;">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:${COLOR_LIGHT_BG};padding:24px 16px;">
<tr><td align="center">
<table role="presentation" width="600" cellpadding="0" cellspacing="0" style="max-width:600px;width:100%;background-color:${COLOR_WHITE};border-radius:12px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.08);">

<!-- Header -->
<tr>
<td style="background:${headerGradient};padding:32px 24px;text-align:center;">
<div style="font-size:40px;line-height:1;margin-bottom:12px;">${headerIcon}</div>
<h1 style="margin:0;color:${COLOR_WHITE};font-size:22px;font-weight:600;letter-spacing:-0.3px;">${headerTitle}</h1>
</td>
</tr>

<!-- Body -->
<tr>
<td style="padding:32px 28px;">
${bodyHtml}
</td>
</tr>

<!-- CTA -->
<tr>
<td style="padding:0 28px 32px;text-align:center;">
<a href="${ctaUrl}" target="_blank" style="display:inline-block;background-color:${BRAND_ACCENT};color:${COLOR_WHITE};padding:14px 36px;border-radius:8px;text-decoration:none;font-weight:600;font-size:15px;letter-spacing:0.2px;">
${ctaText}
</a>
</td>
</tr>

<!-- Footer -->
<tr>
<td style="background-color:${COLOR_DARK};padding:24px 28px;text-align:center;">
<p style="margin:0 0 4px;color:${COLOR_TEXT_TERTIARY};font-size:12px;line-height:1.5;">
FaxBella &mdash; AI-Powered Fax Routing
</p>
<a href="${BASE_URL}" target="_blank" style="color:${COLOR_TEXT_TERTIARY};font-size:12px;text-decoration:none;">faxbella.com</a>
</td>
</tr>

</table>
</td></tr>
</table>
</body>
</html>`;
}

// ---------------------------------------------------------------------------
// Shared helpers
// ---------------------------------------------------------------------------

function formatTimestamp(ts?: number): string {
    const date = ts ? new Date(ts) : new Date();
    return date.toLocaleString('en-US', {
        dateStyle: 'long',
        timeStyle: 'short',
        timeZone: 'America/New_York',
    });
}

function detailRow(label: string, value: string): string {
    return `<tr>
<td style="padding:10px 16px;color:${COLOR_TEXT_SECONDARY};font-size:14px;border-bottom:1px solid #f1f5f9;">${label}</td>
<td style="padding:10px 16px;color:${COLOR_TEXT_PRIMARY};font-size:14px;font-weight:600;text-align:right;border-bottom:1px solid #f1f5f9;">${value}</td>
</tr>`;
}

function detailsTable(rows: string): string {
    return `<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:#f8fafc;border-radius:8px;overflow:hidden;margin:20px 0;">
${rows}
</table>`;
}

/**
 * Escape HTML special characters to prevent XSS in email templates.
 */
function escapeHtml(str: string): string {
    return str
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;')
        .replace(/'/g, '&#39;');
}

interface SendResult {
    success: boolean;
    error?: string;
}

async function sendViaEmailIt(
    to: string,
    subject: string,
    html: string
): Promise<SendResult> {
    const emailitKey = process.env.EMAILIT_API_KEY;

    if (!emailitKey) {
        console.warn('[NOTIFICATIONS] EMAILIT_API_KEY not set -- skipping email');
        return { success: false, error: 'EMAILIT_API_KEY not configured' };
    }

    try {
        const response = await fetch(EMAILIT_ENDPOINT, {
            method: 'POST',
            headers: {
                Authorization: `Bearer ${emailitKey}`,
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({
                from: FROM_ADDRESS,
                to,
                subject,
                html,
            }),
        });

        if (!response.ok) {
            const body = await response.text();
            console.error(
                `[NOTIFICATIONS] EmailIt returned ${response.status}: ${body}`
            );
            return {
                success: false,
                error: `EmailIt HTTP ${response.status}`,
            };
        }

        return { success: true };
    } catch (err) {
        const message = err instanceof Error ? err.message : 'Unknown error';
        console.error('[NOTIFICATIONS] EmailIt request failed:', message);
        return { success: false, error: message };
    }
}

// ---------------------------------------------------------------------------
// 1. Fax Sent Confirmation
// ---------------------------------------------------------------------------

export const sendFaxConfirmation = internalAction({
    args: {
        customerEmail: v.string(),
        recipientNumber: v.string(),
        recipientName: v.optional(v.string()),
        subject: v.optional(v.string()),
        faxId: v.string(),
    },
    handler: async (_ctx, args): Promise<SendResult> => {
        const rawDisplayName = args.recipientName || args.recipientNumber;
        const displayName = escapeHtml(rawDisplayName);
        const safeNumber = escapeHtml(args.recipientNumber);
        const safeSubject = escapeHtml(args.subject || 'N/A');
        const safeFaxId = escapeHtml(args.faxId);

        const bodyHtml = `
<h2 style="margin:0 0 8px;color:${COLOR_TEXT_PRIMARY};font-size:20px;font-weight:600;">Fax Sent Successfully</h2>
<p style="margin:0 0 24px;color:${COLOR_TEXT_SECONDARY};font-size:15px;line-height:1.6;">
Your fax to <strong>${displayName}</strong> has been delivered. Here are the details:
</p>

${detailsTable(
    detailRow('To', displayName) +
    detailRow('Number', safeNumber) +
    detailRow('Subject', safeSubject) +
    detailRow('Fax ID', safeFaxId) +
    detailRow('Sent', formatTimestamp())
)}

<p style="margin:20px 0 0;color:${COLOR_TEXT_SECONDARY};font-size:14px;line-height:1.5;">
You can view the full details and delivery status in your dashboard.
</p>`;

        const html = buildEmailHtml({
            headerGradient: 'linear-gradient(135deg, #16a34a, #22c55e)',
            headerIcon: '&#10003;',
            headerTitle: 'Fax Delivered',
            bodyHtml,
            ctaText: 'View in Dashboard',
            ctaUrl: `${BASE_URL}/dashboard/sent`,
        });

        return sendViaEmailIt(
            args.customerEmail,
            `Your fax to ${displayName} was sent`,
            html
        );
    },
});

// ---------------------------------------------------------------------------
// 2. Fax Delivery Failure Alert
// ---------------------------------------------------------------------------

export const sendFaxFailureAlert = internalAction({
    args: {
        customerEmail: v.string(),
        recipientNumber: v.string(),
        recipientName: v.optional(v.string()),
        error: v.string(),
        faxId: v.string(),
    },
    handler: async (_ctx, args): Promise<SendResult> => {
        const rawDisplayName = args.recipientName || args.recipientNumber;
        const displayName = escapeHtml(rawDisplayName);
        const safeNumber = escapeHtml(args.recipientNumber);
        const safeError = escapeHtml(args.error);
        const safeFaxId = escapeHtml(args.faxId);

        const bodyHtml = `
<h2 style="margin:0 0 8px;color:${COLOR_TEXT_PRIMARY};font-size:20px;font-weight:600;">Fax Delivery Failed</h2>
<p style="margin:0 0 24px;color:${COLOR_TEXT_SECONDARY};font-size:15px;line-height:1.6;">
We were unable to deliver your fax to <strong>${displayName}</strong>. You can retry from your dashboard.
</p>

<div style="background-color:#fef2f2;border:1px solid #fecaca;border-radius:8px;padding:16px;margin:0 0 24px;">
<p style="margin:0;color:#991b1b;font-size:14px;font-weight:600;">Error Details</p>
<p style="margin:6px 0 0;color:#b91c1c;font-size:14px;line-height:1.5;">${safeError}</p>
</div>

${detailsTable(
    detailRow('To', displayName) +
    detailRow('Number', safeNumber) +
    detailRow('Fax ID', safeFaxId) +
    detailRow('Attempted', formatTimestamp())
)}

<p style="margin:20px 0 0;color:${COLOR_TEXT_SECONDARY};font-size:14px;line-height:1.5;">
If the problem persists, please check the recipient number and try again.
</p>`;

        const html = buildEmailHtml({
            headerGradient: 'linear-gradient(135deg, #dc2626, #ef4444)',
            headerIcon: '&#9888;',
            headerTitle: 'Delivery Failed',
            bodyHtml,
            ctaText: 'Retry in Dashboard',
            ctaUrl: `${BASE_URL}/dashboard/sent`,
        });

        return sendViaEmailIt(
            args.customerEmail,
            `Fax delivery failed - ${displayName}`,
            html
        );
    },
});

// ---------------------------------------------------------------------------
// 3. Inbound Fax Received (AI-Analyzed)
// ---------------------------------------------------------------------------

export const sendFaxReceivedNotification = internalAction({
    args: {
        customerEmail: v.string(),
        fromNumber: v.string(),
        documentType: v.optional(v.string()),
        urgency: v.optional(v.string()),
        urgencyReason: v.optional(v.string()),
        aiSummary: v.optional(v.string()),
        faxId: v.string(),
    },
    handler: async (_ctx, args): Promise<SendResult> => {
        const isUrgent = args.urgency === 'urgent';
        const safeFromNumber = escapeHtml(args.fromNumber);
        const safeFaxId = escapeHtml(args.faxId);

        // Document type badge
        const docTypeLabel = escapeHtml(
            args.documentType
                ? args.documentType
                      .replace(/_/g, ' ')
                      .replace(/\b\w/g, (c: string) => c.toUpperCase())
                : 'Document'
        );

        const docTypeBadge = `<span style="display:inline-block;background-color:#e2e8f0;color:#475569;padding:6px 14px;border-radius:20px;font-size:13px;font-weight:600;">${docTypeLabel}</span>`;

        const urgencyBadge = isUrgent
            ? `<span style="display:inline-block;background-color:#ef4444;color:${COLOR_WHITE};padding:6px 14px;border-radius:20px;font-size:13px;font-weight:700;margin-left:8px;">URGENT</span>`
            : '';

        const safeUrgencyReason = escapeHtml(args.urgencyReason || 'This fax has been flagged as urgent and requires immediate attention.');
        const urgencyBox = isUrgent
            ? `<div style="background-color:#fef2f2;border:1px solid #fecaca;border-radius:8px;padding:16px;margin:0 0 24px;">
<p style="margin:0;color:#991b1b;font-size:14px;font-weight:600;">Urgent Fax</p>
<p style="margin:6px 0 0;color:#b91c1c;font-size:14px;line-height:1.5;">${safeUrgencyReason}</p>
</div>`
            : '';

        const safeAiSummary = args.aiSummary ? escapeHtml(args.aiSummary) : '';
        const aiSummaryBlock = safeAiSummary
            ? `<div style="background-color:#f0fdf4;border:1px solid #bbf7d0;border-radius:8px;padding:16px;margin:0 0 24px;">
<p style="margin:0;color:#166534;font-size:14px;font-weight:600;">AI Summary</p>
<p style="margin:6px 0 0;color:#15803d;font-size:14px;line-height:1.5;">${safeAiSummary}</p>
</div>`
            : '';

        const bodyHtml = `
<h2 style="margin:0 0 8px;color:${COLOR_TEXT_PRIMARY};font-size:20px;font-weight:600;">New Fax Received</h2>
<p style="margin:0 0 16px;color:${COLOR_TEXT_SECONDARY};font-size:15px;line-height:1.6;">
A new fax from <strong>${safeFromNumber}</strong> has been received and analyzed by AI.
</p>

<div style="text-align:center;margin:0 0 20px;">
${docTypeBadge}${urgencyBadge}
</div>

${urgencyBox}
${aiSummaryBlock}

${detailsTable(
    detailRow('From', safeFromNumber) +
    detailRow('Document Type', docTypeLabel) +
    detailRow('Urgency', isUrgent ? 'Urgent' : escapeHtml(args.urgency || 'Routine')) +
    detailRow('Fax ID', safeFaxId) +
    detailRow('Received', formatTimestamp())
)}`;

        const subjectPrefix = isUrgent ? 'URGENT: ' : '';
        const headerGradient = isUrgent
            ? 'linear-gradient(135deg, #dc2626, #ef4444)'
            : 'linear-gradient(135deg, #2563eb, #3b82f6)';
        const headerIcon = isUrgent ? '&#9888;' : '&#128228;';

        const html = buildEmailHtml({
            headerGradient,
            headerIcon,
            headerTitle: 'Fax Received',
            bodyHtml,
            ctaText: 'View Fax Details',
            ctaUrl: `${BASE_URL}/dashboard/inbox/${args.faxId}`,
        });

        return sendViaEmailIt(
            args.customerEmail,
            `${subjectPrefix}New fax received from ${args.fromNumber}`,
            html
        );
    },
});

// ---------------------------------------------------------------------------
// 4. Weekly Activity Digest
// ---------------------------------------------------------------------------

export const sendWeeklyDigest = internalAction({
    args: {
        customerEmail: v.string(),
        totalReceived: v.number(),
        totalSent: v.number(),
        urgentCount: v.number(),
        topDocumentTypes: v.array(
            v.object({ type: v.string(), count: v.number() })
        ),
        periodStart: v.string(),
        periodEnd: v.string(),
    },
    handler: async (_ctx, args): Promise<SendResult> => {
        const totalFaxes = args.totalReceived + args.totalSent;

        // Stats grid (3 columns)
        const statsGrid = `
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="margin:0 0 24px;">
<tr>
<td width="33%" style="padding:8px;text-align:center;">
<div style="background-color:#f0f9ff;border-radius:10px;padding:20px 12px;">
<p style="margin:0;font-size:28px;font-weight:700;color:#2563eb;">${args.totalReceived}</p>
<p style="margin:6px 0 0;font-size:13px;color:${COLOR_TEXT_SECONDARY};">Received</p>
</div>
</td>
<td width="33%" style="padding:8px;text-align:center;">
<div style="background-color:#f0fdf4;border-radius:10px;padding:20px 12px;">
<p style="margin:0;font-size:28px;font-weight:700;color:#16a34a;">${args.totalSent}</p>
<p style="margin:6px 0 0;font-size:13px;color:${COLOR_TEXT_SECONDARY};">Sent</p>
</div>
</td>
<td width="33%" style="padding:8px;text-align:center;">
<div style="background-color:${args.urgentCount > 0 ? '#fef2f2' : '#f8fafc'};border-radius:10px;padding:20px 12px;">
<p style="margin:0;font-size:28px;font-weight:700;color:${args.urgentCount > 0 ? '#dc2626' : COLOR_TEXT_PRIMARY};">${args.urgentCount}</p>
<p style="margin:6px 0 0;font-size:13px;color:${COLOR_TEXT_SECONDARY};">Urgent</p>
</div>
</td>
</tr>
</table>`;

        // Document type breakdown
        let docTypeRows = '';
        if (args.topDocumentTypes.length > 0) {
            const docRows = args.topDocumentTypes
                .map((dt) => {
                    const label = escapeHtml(
                        dt.type
                            .replace(/_/g, ' ')
                            .replace(/\b\w/g, (c: string) => c.toUpperCase())
                    );
                    const percentage =
                        totalFaxes > 0
                            ? Math.round((dt.count / totalFaxes) * 100)
                            : 0;
                    return `<tr>
<td style="padding:10px 16px;color:${COLOR_TEXT_PRIMARY};font-size:14px;border-bottom:1px solid #f1f5f9;">${label}</td>
<td style="padding:10px 16px;color:${COLOR_TEXT_SECONDARY};font-size:14px;text-align:center;border-bottom:1px solid #f1f5f9;">${dt.count}</td>
<td style="padding:10px 16px;text-align:right;border-bottom:1px solid #f1f5f9;">
<div style="background-color:#e2e8f0;border-radius:4px;height:8px;width:100%;overflow:hidden;">
<div style="background-color:${BRAND_ACCENT};height:8px;width:${percentage}%;border-radius:4px;"></div>
</div>
</td>
</tr>`;
                })
                .join('');

            docTypeRows = `
<h3 style="margin:24px 0 12px;color:${COLOR_TEXT_PRIMARY};font-size:16px;font-weight:600;">Document Types</h3>
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:#f8fafc;border-radius:8px;overflow:hidden;">
<tr>
<th style="padding:10px 16px;color:${COLOR_TEXT_SECONDARY};font-size:12px;text-align:left;text-transform:uppercase;letter-spacing:0.5px;border-bottom:1px solid #e2e8f0;">Type</th>
<th style="padding:10px 16px;color:${COLOR_TEXT_SECONDARY};font-size:12px;text-align:center;text-transform:uppercase;letter-spacing:0.5px;border-bottom:1px solid #e2e8f0;">Count</th>
<th style="padding:10px 16px;color:${COLOR_TEXT_SECONDARY};font-size:12px;text-align:right;text-transform:uppercase;letter-spacing:0.5px;border-bottom:1px solid #e2e8f0;">Share</th>
</tr>
${docRows}
</table>`;
        }

        const bodyHtml = `
<h2 style="margin:0 0 8px;color:${COLOR_TEXT_PRIMARY};font-size:20px;font-weight:600;">Weekly Summary</h2>
<p style="margin:0 0 24px;color:${COLOR_TEXT_SECONDARY};font-size:15px;line-height:1.6;">
Here is your fax activity for <strong>${escapeHtml(args.periodStart)}</strong> to <strong>${escapeHtml(args.periodEnd)}</strong>.
</p>

${statsGrid}
${docTypeRows}`;

        const html = buildEmailHtml({
            headerGradient: `linear-gradient(135deg, ${BRAND_ACCENT}, #f97316)`,
            headerIcon: '&#128202;',
            headerTitle: 'Weekly Report',
            bodyHtml,
            ctaText: 'Open Dashboard',
            ctaUrl: `${BASE_URL}/dashboard`,
        });

        return sendViaEmailIt(
            args.customerEmail,
            `Your FaxBella Weekly Summary - ${escapeHtml(args.periodStart)} to ${escapeHtml(args.periodEnd)}`,
            html
        );
    },
});
