/* eslint-disable @typescript-eslint/ban-ts-comment */
// @ts-nocheck - Types are generated by Convex at deploy time
/**
 * Whop.com - Backup Payment Processor for FaxBella
 *
 * Whop is available as an alternative to Stripe, controlled by an admin
 * toggle stored in the paymentSettings table. Both processors coexist;
 * only the active one processes new subscriptions.
 *
 * Admin flow:
 *   1. Call getActiveProcessor() to check which is active
 *   2. Call setActiveProcessor('whop') or setActiveProcessor('stripe') to toggle
 *   3. New subscriptions use the active processor; existing subscriptions
 *      continue on their original processor until renewal.
 *
 * Whop API docs: https://dev.whop.com
 */

import { action, mutation, query, internalMutation, internalAction } from './_generated/server';
import { v } from 'convex/values';
import { internal } from './_generated/api';

// ─── Plan Mapping ──────────────────────────────────────────

// Whop plan IDs must be configured in the Whop Dashboard
// Map FaxBella plan names to Whop plan/product IDs
const WHOP_PLAN_IDS: Record<string, string> = {
    standard: 'plan_faxbella_standard',
    daypass: 'plan_faxbella_daypass',
    // Legacy support
    starter: 'plan_faxbella_standard',
    business: 'plan_faxbella_standard',
    enterprise: 'plan_faxbella_standard',
};

const PLAN_PRICES: Record<string, number> = {
    standard: 5500,    // $55.00 per 500-fax block
    daypass: 900,      // $9.00 per 5-doc day pass
    // Legacy support
    starter: 5500,
    business: 5500,
    enterprise: 5500,
};

// ─── Admin: Payment Processor Toggle ───────────────────────

/**
 * Get the currently active payment processor. Defaults to 'stripe'.
 */
export const getActiveProcessor = query({
    args: {},
    handler: async (ctx) => {
        const settings = await ctx.db
            .query('paymentSettings')
            .withIndex('by_key', (q) => q.eq('key', 'global'))
            .first();

        return {
            activeProcessor: settings?.activeProcessor || 'stripe',
            updatedAt: settings?.updatedAt || null,
            updatedBy: settings?.updatedBy || null,
        };
    },
});

/**
 * Admin toggle: Switch the active payment processor between Stripe and Whop.
 * Only affects NEW subscriptions. Existing subscriptions continue on their
 * original processor until they renew.
 */
export const setActiveProcessor = mutation({
    args: {
        processor: v.string(), // 'stripe' | 'whop'
        adminEmail: v.string(),
    },
    handler: async (ctx, args) => {
        if (args.processor !== 'stripe' && args.processor !== 'whop') {
            throw new Error('Invalid processor. Must be "stripe" or "whop".');
        }

        const existing = await ctx.db
            .query('paymentSettings')
            .withIndex('by_key', (q) => q.eq('key', 'global'))
            .first();

        if (existing) {
            await ctx.db.patch(existing._id, {
                activeProcessor: args.processor,
                updatedAt: Date.now(),
                updatedBy: args.adminEmail,
            });
        } else {
            await ctx.db.insert('paymentSettings', {
                key: 'global',
                activeProcessor: args.processor,
                updatedAt: Date.now(),
                updatedBy: args.adminEmail,
            });
        }

        return {
            success: true,
            activeProcessor: args.processor,
        };
    },
});

// ─── Whop Checkout ─────────────────────────────────────────

/**
 * Create a Whop checkout session for a customer.
 * Returns a checkout URL that the customer should be redirected to.
 */
export const createCheckoutSession = action({
    args: {
        email: v.string(),
        plan: v.string(), // 'standard' (legacy: 'starter' | 'business' | 'enterprise')
    },
    handler: async (ctx, args) => {
        const whopApiKey = process.env.WHOP_API_KEY;
        if (!whopApiKey) {
            throw new Error('Whop API key not configured');
        }

        const planId = WHOP_PLAN_IDS[args.plan];
        if (!planId) {
            throw new Error(`Invalid plan: ${args.plan}`);
        }

        try {
            const response = await fetch('https://api.whop.com/v5/checkout_sessions', {
                method: 'POST',
                headers: {
                    'Authorization': `Bearer ${whopApiKey}`,
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify({
                    plan_id: planId,
                    metadata: {
                        email: args.email,
                        faxbella_plan: args.plan,
                    },
                    success_url: 'https://faxbella.com/dashboard?payment=success',
                    cancel_url: 'https://faxbella.com/signup?payment=cancelled',
                }),
            });

            if (!response.ok) {
                const errorData = await response.text();
                throw new Error(`Whop API error: ${response.status} - ${errorData}`);
            }

            const data = await response.json();

            return {
                checkoutUrl: data.checkout_url || data.url,
                sessionId: data.id,
            };
        } catch (error) {
            const msg = error instanceof Error ? error.message : 'Failed to create Whop checkout';
            console.error('[WHOP] Checkout error:', msg);
            throw new Error(msg);
        }
    },
});

// ─── Whop Webhook Processing ───────────────────────────────

/**
 * Internal mutation to create or update a customer from a Whop webhook event.
 */
export const handleWhopSubscriptionCreated = internalMutation({
    args: {
        email: v.string(),
        plan: v.string(),
        whopMembershipId: v.string(),
        whopCustomerId: v.string(),
    },
    handler: async (ctx, args) => {
        // Check if customer already exists
        const existing = await ctx.db
            .query('customers')
            .withIndex('by_email', (q) => q.eq('email', args.email))
            .first();

        const planLimits: Record<string, { faxes: number }> = {
            standard: { faxes: 500 },
            daypass: { faxes: 5 },
            // Legacy support
            starter: { faxes: 500 },
            business: { faxes: 500 },
            enterprise: { faxes: 500 },
        };

        const limits = planLimits[args.plan] || planLimits.standard;

        if (existing) {
            // Update existing customer with Whop info
            await ctx.db.patch(existing._id, {
                plan: args.plan,
                planStatus: 'active',
                // Store Whop IDs in Stripe fields with whop_ prefix for identification
                stripeCustomerId: `whop_${args.whopCustomerId}`,
                stripeSubscriptionId: `whop_${args.whopMembershipId}`,
                faxesLimit: limits.faxes,
                updatedAt: Date.now(),
            });
            return { customerId: existing._id, updated: true };
        }

        // Create new customer
        const chars = 'ABCDEFGHJKLMNPQRSTUVWXYZabcdefghjkmnpqrstuvwxyz23456789';
        let webhookSecret = 'faxai_';
        for (let i = 0; i < 32; i++) {
            webhookSecret += chars[crypto.getRandomValues(new Uint32Array(1))[0] % chars.length];
        }

        const customerId = await ctx.db.insert('customers', {
            email: args.email,
            stripeCustomerId: `whop_${args.whopCustomerId}`,
            stripeSubscriptionId: `whop_${args.whopMembershipId}`,
            plan: args.plan,
            planStatus: 'active',
            webhookSecret,
            faxesThisMonth: 0,
            faxesLimit: limits.faxes,
            createdAt: Date.now(),
        });

        return { customerId, updated: false };
    },
});

/**
 * Internal mutation to handle Whop subscription cancellation.
 */
export const handleWhopSubscriptionCancelled = internalMutation({
    args: {
        whopMembershipId: v.string(),
    },
    handler: async (ctx, args) => {
        // Find customer by Whop membership ID
        const customers = await ctx.db.query('customers').collect();
        const customer = customers.find(
            (c) => c.stripeSubscriptionId === `whop_${args.whopMembershipId}`
        );

        if (!customer) {
            console.error(`[WHOP] Customer not found for membership: ${args.whopMembershipId}`);
            return { success: false };
        }

        await ctx.db.patch(customer._id, {
            planStatus: 'canceled',
            updatedAt: Date.now(),
        });

        // Send cancellation email via EmailIt (ONLY email provider)
        return { success: true, email: customer.email };
    },
});

/**
 * Internal action to send Whop-related emails via EmailIt.
 */
export const sendWhopEmail = internalAction({
    args: {
        to: v.string(),
        subject: v.string(),
        html: v.string(),
    },
    handler: async (_ctx, args) => {
        const emailitKey = process.env.EMAILIT_API_KEY;
        if (!emailitKey) {
            console.error('[WHOP] EmailIt API key not configured');
            return { success: false };
        }

        try {
            await fetch('https://api.emailit.com/v1/emails', {
                method: 'POST',
                headers: {
                    'Authorization': `Bearer ${emailitKey}`,
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify({
                    from: 'FaxBella <notifications@faxbella.com>',
                    to: args.to,
                    subject: args.subject,
                    html: args.html,
                }),
            });
            return { success: true };
        } catch (error) {
            console.error('[WHOP] Email send failed:', error);
            return { success: false };
        }
    },
});

// ─── Whop Membership Management ────────────────────────────

/**
 * Check a customer's Whop membership status.
 */
export const checkMembershipStatus = action({
    args: {
        whopMembershipId: v.string(),
    },
    handler: async (_ctx, args) => {
        const whopApiKey = process.env.WHOP_API_KEY;
        if (!whopApiKey) {
            throw new Error('Whop API key not configured');
        }

        try {
            const response = await fetch(
                `https://api.whop.com/v5/memberships/${args.whopMembershipId}`,
                {
                    headers: {
                        'Authorization': `Bearer ${whopApiKey}`,
                    },
                }
            );

            if (!response.ok) {
                throw new Error(`Whop API error: ${response.status}`);
            }

            const data = await response.json();

            return {
                status: data.status, // 'active', 'past_due', 'cancelled', etc.
                planId: data.plan_id,
                renewalDate: data.renewal_period_end,
                cancelAtPeriodEnd: data.cancel_at_period_end,
            };
        } catch (error) {
            const msg = error instanceof Error ? error.message : 'Failed to check Whop membership';
            console.error('[WHOP] Membership check error:', msg);
            throw new Error(msg);
        }
    },
});

/**
 * Cancel a Whop membership.
 */
export const cancelMembership = action({
    args: {
        whopMembershipId: v.string(),
    },
    handler: async (ctx, args) => {
        const whopApiKey = process.env.WHOP_API_KEY;
        if (!whopApiKey) {
            throw new Error('Whop API key not configured');
        }

        try {
            const response = await fetch(
                `https://api.whop.com/v5/memberships/${args.whopMembershipId}`,
                {
                    method: 'POST',
                    headers: {
                        'Authorization': `Bearer ${whopApiKey}`,
                        'Content-Type': 'application/json',
                    },
                    body: JSON.stringify({
                        cancel_at_period_end: true,
                    }),
                }
            );

            if (!response.ok) {
                throw new Error(`Whop API error: ${response.status}`);
            }

            return { success: true };
        } catch (error) {
            const msg = error instanceof Error ? error.message : 'Failed to cancel Whop membership';
            console.error('[WHOP] Cancel error:', msg);
            throw new Error(msg);
        }
    },
});
