/* eslint-disable */
/**
 * Generated by convex codegen.
 *
 * This is a stub — overwritten by `npx convex dev`.
 */
import type { AnyApi } from "convex/server";

declare const api: AnyApi;
declare const internal: AnyApi;
export { api, internal };
