/* eslint-disable */
/**
 * Generated by convex codegen.
 *
 * This is a stub file — it will be overwritten by `npx convex dev`.
 *
 * @ts-nocheck
 */
import { anyApi } from "convex/server";

export const api = anyApi;
export const internal = anyApi;
