/* eslint-disable */
/**
 * Generated by convex codegen.
 *
 * This is a stub — overwritten by `npx convex dev`.
 */
import type { GenericId } from "convex/values";

export type Id<TableName extends string> = GenericId<TableName>;
