export const SITE_CONFIG = {
  name: 'FaxBella',
  domain: 'faxbella.com',
  tagline: 'AI-Powered Fax Routing',
  description: 'Every fax finds its person, instantly.',
  supportEmail: 'support@faxbella.com',
  company: 'FaxBella',
  year: new Date().getFullYear(),
} as const;

export const ADMIN_EMAILS = [
  'hellonolen@gmail.com',
  'nolen@doclish.com',
  'tracyhogan76@gmail.com',
] as const;

export const ROUTES = {
  home: '/',
  features: '/features',
  howItWorks: '/how-it-works',
  pricing: '/pricing',
  login: '/login',
  signup: '/signup',
  privacy: '/privacy',
  terms: '/terms',
  dashboard: '/dashboard',
  inbox: '/dashboard/inbox',
  send: '/dashboard/send',
  sent: '/dashboard/sent',
  recipients: '/dashboard/recipients',
  library: '/dashboard/library',
  workflows: '/dashboard/workflows',
  queue: '/dashboard/queue',
  settings: '/dashboard/settings',
  billing: '/dashboard/billing',
} as const;

export const PLAN = {
  key: 'standard',
  name: 'FaxBella Membership',
  price: 55,
  faxBlock: 1000,
  recipientLimit: Infinity,
  features: [
    '1,000 faxes per month (send + receive)',
    'Unlimited recipients',
    'AI-powered routing',
    'Priority detection & routing',
    'Email + webhook delivery',
    'Send faxes',
    'Full dashboard & analytics',
    'Export reports',
    'API access',
    'Priority support',
  ],
} as const;

export const DAY_PASS = {
  key: 'daypass',
  name: 'Day Pass',
  price: 9,
  faxBlock: 5,
  recipientLimit: Infinity,
  duration: '8 hours',
  features: [
    '5 documents per pass',
    '8-hour access window',
    'AI-powered routing',
    'Send + receive faxes',
    'Full dashboard access',
    'Auto-expand available',
  ],
} as const;

// Keep backward compatibility
export const PLANS = {
  standard: PLAN,
  daypass: DAY_PASS,
} as const;

export const STRIPE_PRICE_MAP: Record<string, string> = {
  standard: 'STRIPE_PRICE_STANDARD_MONTHLY',
  daypass: 'STRIPE_PRICE_DAYPASS',
};

export const FEATURES = [
  {
    title: 'Smart Routing',
    description: 'Every fax is read, understood, and delivered to the right person — without anyone lifting a finger.',
    icon: 'Brain' as const,
  },
  {
    title: 'Instant Delivery',
    description: 'Faxes land in the right inbox within seconds. No more waiting, no more wondering.',
    icon: 'Zap' as const,
  },
  {
    title: 'Priority Detection',
    description: 'Urgent referrals and lab results are flagged automatically so nothing critical gets buried.',
    icon: 'FileSearch' as const,
  },
  {
    title: 'Secure & Private',
    description: 'Your patient data stays protected. Encrypted processing, no content storage, total peace of mind.',
    icon: 'Shield' as const,
  },
  {
    title: 'Complete Visibility',
    description: 'See where every fax went, when it arrived, and how confident the match was — all from one dashboard.',
    icon: 'BarChart3' as const,
  },
  {
    title: 'Easy Setup',
    description: 'Keep your existing fax number. Connect in two minutes. No new equipment, no learning curve.',
    icon: 'Plug' as const,
  },
] as const;

export const STEPS = [
  {
    number: '01',
    title: 'Connect Your Fax Number',
    description: 'Enter your existing fax number and you\'re connected. Takes about two minutes, no new equipment needed.',
  },
  {
    number: '02',
    title: 'Add Your Team',
    description: 'Tell us who receives faxes — by name, department, or document type. We handle the rest.',
  },
  {
    number: '03',
    title: 'Faxes Route Themselves',
    description: 'Every incoming fax is read, sorted, and delivered to the right person automatically. You never touch a fax tray again.',
  },
] as const;

export const NAV_ITEMS = [
  { label: 'Features', href: '/features' },
  { label: 'How It Works', href: '/how-it-works' },
  { label: 'Pricing', href: '/pricing' },
] as const;

export const DASHBOARD_NAV_ITEMS = [
  { label: 'Overview', href: '/dashboard', icon: 'LayoutDashboard' as const },
  { label: 'Inbox', href: '/dashboard/inbox', icon: 'Inbox' as const },
  { label: 'Send Fax', href: '/dashboard/send', icon: 'Send' as const },
  { label: 'Sent', href: '/dashboard/sent', icon: 'SendHorizontal' as const },
  { label: 'Library', href: '/dashboard/library', icon: 'FolderOpen' as const },
  { label: 'Workflows', href: '/dashboard/workflows', icon: 'Workflow' as const },
  { label: 'Queue', href: '/dashboard/queue', icon: 'ListChecks' as const },
  { label: 'Recipients', href: '/dashboard/recipients', icon: 'Users' as const },
  { label: 'Settings', href: '/dashboard/settings', icon: 'Settings' as const },
  { label: 'Billing', href: '/dashboard/billing', icon: 'CreditCard' as const },
] as const;

export const DASHBOARD_STATS = [
  { label: 'Faxes This Month', value: '47', limit: '1000', icon: 'FileText' as const },
  { label: 'Recipients', value: '4', icon: 'Users' as const },
  { label: 'Routing Accuracy', value: '94%', icon: 'Target' as const },
  { label: 'Avg. Processing', value: '3.2s', icon: 'Clock' as const },
] as const;

export const MOCK_FAXES = [
  { from: '+1 (555) 234-5678', type: 'Lab Results', urgency: 'Urgent', to: 'Dr. Sarah Chen', confidence: '97%', time: '2 min ago' },
  { from: '+1 (555) 876-5432', type: 'Referral', urgency: 'Routine', to: 'Front Desk', confidence: '91%', time: '14 min ago' },
  { from: '+1 (555) 345-6789', type: 'Insurance Auth', urgency: 'Routine', to: 'Billing Dept', confidence: '88%', time: '1 hr ago' },
  { from: '+1 (555) 456-7890', type: 'Prescription', urgency: 'Urgent', to: 'Dr. James Park', confidence: '95%', time: '2 hrs ago' },
  { from: '+1 (555) 567-8901', type: 'Medical Records', urgency: 'Routine', to: 'Records Dept', confidence: '92%', time: '3 hrs ago' },
] as const;

export const FAX_STATUS_MAP: Record<string, { label: string; color: string; bg: string }> = {
  pending: { label: 'Pending', color: 'var(--color-warning)', bg: 'var(--color-warning-light)' },
  processing: { label: 'Processing', color: 'var(--color-info)', bg: 'var(--color-info-light)' },
  routed: { label: 'Routed', color: 'var(--color-success)', bg: 'var(--color-success-light)' },
  unroutable: { label: 'Unroutable', color: 'var(--color-vc-text-tertiary)', bg: 'var(--color-vc-surface)' },
  error: { label: 'Error', color: 'var(--color-error)', bg: 'var(--color-error-light)' },
  queued: { label: 'Queued', color: 'var(--color-warning)', bg: 'var(--color-warning-light)' },
  sending: { label: 'Sending', color: 'var(--color-info)', bg: 'var(--color-info-light)' },
  delivered: { label: 'Delivered', color: 'var(--color-success)', bg: 'var(--color-success-light)' },
  failed: { label: 'Failed', color: 'var(--color-error)', bg: 'var(--color-error-light)' },
};

export const URGENCY_MAP: Record<string, { label: string; color: string; bg: string }> = {
  urgent: { label: 'Urgent', color: 'var(--color-vc-accent)', bg: 'rgba(232, 85, 61, 0.08)' },
  routine: { label: 'Routine', color: 'var(--color-vc-text-tertiary)', bg: 'var(--color-vc-surface)' },
  low: { label: 'Low', color: 'var(--color-vc-text-tertiary)', bg: 'var(--color-vc-surface)' },
};

export const DOCUMENT_TYPE_MAP: Record<string, string> = {
  referral: 'Referral',
  prescription_refill: 'Prescription',
  lab_results: 'Lab Results',
  invoice: 'Invoice',
  prior_auth: 'Prior Auth',
  medical_records: 'Medical Records',
  insurance_claim: 'Insurance Claim',
  appointment_request: 'Appointment',
  test_results: 'Test Results',
  discharge_summary: 'Discharge',
  consultation_notes: 'Consultation',
  other: 'Other',
};

export const MOCK_INBOUND_FAXES = [
  {
    id: 'inb_001',
    fromNumber: '+15552345678',
    toNumber: '+15551234567',
    numPages: 3,
    status: 'routed',
    routedTo: 'Dr. Sarah Chen',
    routingConfidence: 0.97,
    routingReason: 'Document contains lab results and bloodwork panel from Quest Diagnostics',
    documentType: 'lab_results',
    urgency: 'urgent',
    urgencyReason: 'Abnormal values detected in CBC panel',
    receivedAt: Date.now() - 2 * 60 * 1000,
    processedAt: Date.now() - 90 * 1000,
  },
  {
    id: 'inb_002',
    fromNumber: '+15558765432',
    toNumber: '+15551234567',
    numPages: 2,
    status: 'routed',
    routedTo: 'Front Desk',
    routingConfidence: 0.91,
    routingReason: 'New patient referral from Dr. Martinez at Valley Orthopedics',
    documentType: 'referral',
    urgency: 'routine',
    urgencyReason: undefined,
    receivedAt: Date.now() - 14 * 60 * 1000,
    processedAt: Date.now() - 13 * 60 * 1000,
  },
  {
    id: 'inb_003',
    fromNumber: '+15553456789',
    toNumber: '+15551234567',
    numPages: 5,
    status: 'routed',
    routedTo: 'Billing Dept',
    routingConfidence: 0.88,
    routingReason: 'Prior authorization request from Aetna for MRI procedure',
    documentType: 'prior_auth',
    urgency: 'routine',
    urgencyReason: undefined,
    receivedAt: Date.now() - 60 * 60 * 1000,
    processedAt: Date.now() - 58 * 60 * 1000,
  },
  {
    id: 'inb_004',
    fromNumber: '+15554567890',
    toNumber: '+15551234567',
    numPages: 1,
    status: 'routed',
    routedTo: 'Dr. James Park',
    routingConfidence: 0.95,
    routingReason: 'Prescription refill request for patient Thompson, lisinopril 10mg',
    documentType: 'prescription_refill',
    urgency: 'urgent',
    urgencyReason: 'Medication refill - patient out of supply',
    receivedAt: Date.now() - 2 * 60 * 60 * 1000,
    processedAt: Date.now() - 118 * 60 * 1000,
  },
  {
    id: 'inb_005',
    fromNumber: '+15555678901',
    toNumber: '+15551234567',
    numPages: 4,
    status: 'processing',
    routedTo: undefined,
    routingConfidence: undefined,
    routingReason: undefined,
    documentType: undefined,
    urgency: undefined,
    urgencyReason: undefined,
    receivedAt: Date.now() - 30 * 1000,
    processedAt: undefined,
  },
  {
    id: 'inb_006',
    fromNumber: '+15556789012',
    toNumber: '+15551234567',
    numPages: 7,
    status: 'routed',
    routedTo: 'Dr. James Park',
    routingConfidence: 0.93,
    routingReason: 'Consultation notes from cardiology specialist regarding patient Davis',
    documentType: 'consultation_notes',
    urgency: 'routine',
    urgencyReason: undefined,
    receivedAt: Date.now() - 3 * 60 * 60 * 1000,
    processedAt: Date.now() - 178 * 60 * 1000,
  },
  {
    id: 'inb_007',
    fromNumber: '+15557890123',
    toNumber: '+15551234567',
    numPages: 2,
    status: 'pending',
    routedTo: undefined,
    routingConfidence: undefined,
    routingReason: undefined,
    documentType: undefined,
    urgency: undefined,
    urgencyReason: undefined,
    receivedAt: Date.now() - 10 * 1000,
    processedAt: undefined,
  },
  {
    id: 'inb_008',
    fromNumber: '+15558901234',
    toNumber: '+15551234567',
    numPages: 1,
    status: 'routed',
    routedTo: 'Front Desk',
    routingConfidence: 0.86,
    routingReason: 'Appointment scheduling request from patient Williams',
    documentType: 'appointment_request',
    urgency: 'routine',
    urgencyReason: undefined,
    receivedAt: Date.now() - 5 * 60 * 60 * 1000,
    processedAt: Date.now() - 298 * 60 * 1000,
  },
  {
    id: 'inb_009',
    fromNumber: '+15559012345',
    toNumber: '+15551234567',
    numPages: 12,
    status: 'routed',
    routedTo: 'Dr. Sarah Chen',
    routingConfidence: 0.94,
    routingReason: 'Discharge summary from Mercy General Hospital, post-surgical follow-up',
    documentType: 'discharge_summary',
    urgency: 'urgent',
    urgencyReason: 'Post-operative patient requires 48-hour follow-up',
    receivedAt: Date.now() - 7 * 60 * 60 * 1000,
    processedAt: Date.now() - 418 * 60 * 1000,
  },
  {
    id: 'inb_010',
    fromNumber: '+15550123456',
    toNumber: '+15551234567',
    numPages: 3,
    status: 'routed',
    routedTo: 'Billing Dept',
    routingConfidence: 0.9,
    routingReason: 'Insurance claim denial from BlueCross BlueShield, claim #BC-2024-8847',
    documentType: 'insurance_claim',
    urgency: 'routine',
    urgencyReason: undefined,
    receivedAt: Date.now() - 24 * 60 * 60 * 1000,
    processedAt: Date.now() - 1438 * 60 * 1000,
  },
];

export const MOCK_OUTBOUND_FAXES = [
  {
    _id: 'outb_001',
    customerId: 'demo_customer_001',
    recipientNumber: '+15559876543',
    recipientName: 'Valley Orthopedics',
    subject: 'Patient Referral - Johnson, M.',
    message: 'Referral for knee evaluation. Patient reports persistent pain for 6 weeks.',
    status: 'delivered',
    providerFaxId: 'hf_fax_a1b2c3d4',
    error: undefined,
    createdAt: Date.now() - 4 * 60 * 60 * 1000,
    sentAt: Date.now() - 237 * 60 * 1000,
  },
  {
    _id: 'outb_002',
    customerId: 'demo_customer_001',
    recipientNumber: '+15551112222',
    recipientName: 'Aetna Prior Auth Dept',
    subject: 'Prior Authorization - MRI Lumbar Spine',
    message: 'Requesting prior authorization for MRI. Clinical notes attached.',
    status: 'delivered',
    providerFaxId: 'hf_fax_e5f6g7h8',
    error: undefined,
    createdAt: Date.now() - 26 * 60 * 60 * 1000,
    sentAt: Date.now() - 1554 * 60 * 1000,
  },
  {
    _id: 'outb_003',
    customerId: 'demo_customer_001',
    recipientNumber: '+15553334444',
    recipientName: 'Quest Diagnostics',
    subject: 'Lab Order - CBC, CMP, Lipid Panel',
    message: undefined,
    status: 'sending',
    providerFaxId: 'hf_fax_i9j0k1l2',
    error: undefined,
    createdAt: Date.now() - 5 * 60 * 1000,
    sentAt: undefined,
  },
  {
    _id: 'outb_004',
    customerId: 'demo_customer_001',
    recipientNumber: '+15555556666',
    recipientName: 'Mercy General Hospital',
    subject: 'Records Request - Patient Davis',
    message: 'Requesting surgical notes and discharge summary from 01/15 procedure.',
    status: 'queued',
    providerFaxId: undefined,
    error: undefined,
    createdAt: Date.now() - 2 * 60 * 1000,
    sentAt: undefined,
  },
  {
    _id: 'outb_005',
    customerId: 'demo_customer_001',
    recipientNumber: '+15557778888',
    recipientName: 'Walgreens Pharmacy #4521',
    subject: 'Prescription - Lisinopril 10mg',
    message: 'New prescription for patient Thompson. See attached Rx.',
    status: 'failed',
    providerFaxId: 'hf_fax_m3n4o5p6',
    error: 'Recipient fax line busy after 3 retry attempts',
    createdAt: Date.now() - 48 * 60 * 60 * 1000,
    sentAt: undefined,
  },
];

export const MOCK_RECIPIENTS = [
  {
    id: 'recip_dr_chen',
    name: 'Dr. Sarah Chen',
    email: 'sarah.chen@riversidemedical.com',
    company: 'Riverside Family Medicine',
    keywords: ['lab results', 'referrals', 'pathology', 'bloodwork', 'test results'],
    deliveryMethod: 'email',
    active: true,
    createdAt: Date.now() - 88 * 24 * 60 * 60 * 1000,
  },
  {
    id: 'recip_front_desk',
    name: 'Front Desk',
    email: 'frontdesk@riversidemedical.com',
    company: 'Riverside Family Medicine',
    keywords: ['general', 'appointments', 'scheduling', 'patient intake', 'records request'],
    deliveryMethod: 'email',
    active: true,
    createdAt: Date.now() - 88 * 24 * 60 * 60 * 1000,
  },
  {
    id: 'recip_billing',
    name: 'Billing Dept',
    email: 'billing@riversidemedical.com',
    company: 'Riverside Family Medicine',
    keywords: ['insurance', 'claims', 'prior authorization', 'invoices', 'denial', 'EOB'],
    deliveryMethod: 'email',
    active: true,
    createdAt: Date.now() - 85 * 24 * 60 * 60 * 1000,
  },
  {
    id: 'recip_dr_park',
    name: 'Dr. James Park',
    email: 'james.park@riversidemedical.com',
    company: 'Riverside Family Medicine',
    keywords: ['prescriptions', 'consultations', 'medication', 'refills', 'specialist notes'],
    deliveryMethod: 'webhook',
    active: true,
    createdAt: Date.now() - 72 * 24 * 60 * 60 * 1000,
  },
];

export const STATS_BAR = [
  { label: 'Faxes Processed', value: '2.4M+' },
  { label: 'Routing Accuracy', value: '97.3%' },
  { label: 'Avg. Processing', value: '<4s' },
  { label: 'Active Clinics', value: '850+' },
] as const;

export const MOCK_DASHBOARD_DATA = {
  customer: {
    _id: 'demo_customer_001',
    email: 'demo@faxbella.com',
    name: 'Riverside Family Medicine',
    plan: 'standard',
    planStatus: 'active',
    faxesThisMonth: 47,
    faxesLimit: 1000,
    recipientLimit: 999999,
    faxNumber: '+15551234567',
    humbleFaxAccessKey: '***configured***',
    humbleFaxSecretKey: '***configured***',
    geminiApiKey: '***configured***',
    createdAt: Date.now() - 90 * 24 * 60 * 60 * 1000,
  },
  recipientsCount: 4,
  recipients: [
    {
      id: 'recip_dr_chen',
      name: 'Dr. Sarah Chen',
      email: 'sarah.chen@riversidemedical.com',
      keywords: ['lab results', 'referrals', 'pathology', 'bloodwork'],
      active: true,
    },
    {
      id: 'recip_front_desk',
      name: 'Front Desk',
      email: 'frontdesk@riversidemedical.com',
      keywords: ['general', 'appointments', 'scheduling', 'patient intake'],
      active: true,
    },
    {
      id: 'recip_billing',
      name: 'Billing Dept',
      email: 'billing@riversidemedical.com',
      keywords: ['insurance', 'claims', 'prior authorization', 'invoices'],
      active: true,
    },
    {
      id: 'recip_dr_park',
      name: 'Dr. James Park',
      email: 'james.park@riversidemedical.com',
      keywords: ['prescriptions', 'consultations', 'medication', 'refills'],
      active: true,
    },
  ],
  recentFaxes: [
    {
      id: 'fax_demo_001',
      fromNumber: '+15552345678',
      status: 'routed',
      confidence: 0.97,
      reason: 'Matched keywords: lab results, bloodwork panel',
      receivedAt: Date.now() - 2 * 60 * 1000,
    },
    {
      id: 'fax_demo_002',
      fromNumber: '+15558765432',
      status: 'routed',
      confidence: 0.91,
      reason: 'Matched keywords: referral, new patient',
      receivedAt: Date.now() - 14 * 60 * 1000,
    },
    {
      id: 'fax_demo_003',
      fromNumber: '+15553456789',
      status: 'routed',
      confidence: 0.88,
      reason: 'Matched keywords: insurance authorization',
      receivedAt: Date.now() - 60 * 60 * 1000,
    },
    {
      id: 'fax_demo_004',
      fromNumber: '+15554567890',
      status: 'routed',
      confidence: 0.95,
      reason: 'Matched keywords: prescription refill request',
      receivedAt: Date.now() - 2 * 60 * 60 * 1000,
    },
    {
      id: 'fax_demo_005',
      fromNumber: '+15555678901',
      status: 'processing',
      confidence: undefined,
      reason: undefined,
      receivedAt: Date.now() - 30 * 1000,
    },
    {
      id: 'fax_demo_006',
      fromNumber: '+15556789012',
      status: 'routed',
      confidence: 0.93,
      reason: 'Matched keywords: consultation notes, specialist',
      receivedAt: Date.now() - 3 * 60 * 60 * 1000,
    },
    {
      id: 'fax_demo_007',
      fromNumber: '+15557890123',
      status: 'pending',
      confidence: undefined,
      reason: undefined,
      receivedAt: Date.now() - 10 * 1000,
    },
    {
      id: 'fax_demo_008',
      fromNumber: '+15558901234',
      status: 'routed',
      confidence: 0.86,
      reason: 'Matched keywords: appointment scheduling',
      receivedAt: Date.now() - 5 * 60 * 60 * 1000,
    },
  ],
};
